site_name: Vaibhav's Technical Notes
site_description: Short nuggets of information, code snippets or articles that I want to keep handy.
copyright: Vaibhav
repo_name: vg-vaibhav/notes
repo_url: https://github.com/vg-vaibhav/vg-vaibhav.github.io/
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
  font:
    text: Inter
    code: IMB Plex Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vg-vaibhav
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/angrykabootar
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/angrykabootar
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/vaibhav-vg
    - icon: fontawesome/brands/unsplash
      link: https://unsplash.com/@vgvaibhav

nav:
  - Home: index.md
  - Postgres:
    - postgres/create-super-user.md
    - postgres/last-vacuum.md
    - postgres/check-idle-queries.md
    - postgres/count-estimate.md
  - Kafka:
    - kafka/reset-offset.md
  - Redis:
    - redis/data-modification.md
  - Miscellaneous:
    - miscellaneous/commands.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.details
  - footnotes